export const API = "API";

export const CREATE_PATIENT_IS_LOADING = "CREATE_PATIENT_IS_LOADING";

export const CREATE_PATIENT_HAS_ERRORED = "CREATE_PATIENT_HAS_ERRORED";

export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";

// export const PATIENTS_HAS_ERRORED = "PATIENTS_HAS_ERRORED";

// export const PATIENTS_IS_LOADING = "PATIENTS_IS_LOADING";

// export const PATIENTS_FETCH_DATA_SUCCESS = "PATIENTS_FETCH_DATA_SUCCESS";

// export const INITIAL_FETCH_SUCCESS = "INITIAL_FETCH_SUCCESS";

// export const LANGUAGES_FETCH_DATA_IS_LOADING =
//   "LANGUAGES_FETCH_DATA_IS_LOADING";

// export const LANGUAGES_FETCH_DATA_HAS_ERRORED =
//   "LANGUAGES_FETCH_DATA_HAS_ERRORED";

// export const LANGUAGES_FETCH_DATA_SUCCESS = "LANGUAGES_FETCH_DATA_SUCCESS";

// export const LANGUAGES_INITIAL_FETCH_SUCCESS =
//   "LANGUAGES_INITIAL_FETCH_SUCCESS";

export const FETCH_ACTION_TYPE = type => ({
  success: `${type}_SUCCESS`,
  error: `${type}_ERROR`,
  apiStart: `${type}_API_START`,
  apiDone: `${type}_API_DONE`
});

export const FETCH_PATIENTS_SUCCESS = "FETCH_PATIENTS_SUCCESS";

export const FETCH_PATIENTS_ERROR = "FETCH_PATIENTS_ERROR";

export const FETCH_PATIENTS_API_START = "FETCH_PATIENTS_API_START";

export const FETCH_PATIENTS_API_DONE = "FETCH_PATIENTS_API_DONE";

export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";

export const FETCH_LANGUAGES_ERROR = "FETCH_LANGUAGES_ERROR";

export const FETCH_LANGUAGES_API_START = "FETCH_LANGUAGES_API_START";

export const FETCH_LANGUAGES_API_DONE = "FETCH_LANGUAGES_API_DONE";
