export const CREATE_PATIENT = "CREATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const PATIENTS_HAS_ERRORED = "PATIENTS_HAS_ERRORED";
export const PATIENTS_IS_LOADING = "PATIENTS_IS_LOADING";
export const PATIENTS_FETCH_DATA_SUCCESS = "PATIENTS_FETCH_DATA_SUCCESS";
